import {Dimensions, StyleSheet} from 'react-native';
import theme from './theme';

export const themeStyle = StyleSheet.create({
  textSmall: {
    fontFamily: theme.fonts.uber,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 17,
    letterSpacing: 0,
    textAlign: 'left',
  },
  textMedium: {
    fontFamily: theme.fonts.uber,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 21.05,
    letterSpacing: 0,
    textAlign: 'left',
  },
  poppinsTextMedium: {
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 30,
    letterSpacing: 0,
    textAlign: 'left',
  },
  poppinsTextBold: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
  },
  poppinsTextSmall: {
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'left',
  },
  greyBoxCase: {
    width: 355,
    height: 'auto',
    borderRadius: 15,
    backgroundColor: theme.colors.grey,
    alignSelf: 'center',
    margin: 4,
    padding: 20,
    paddingVertical: 35,
  },
  blueBoxEvents: {
    width: 230,
    height: 151,
    backgroundColor: theme.colors.blueBoxBackground,
    borderColor: theme.colors.blueBoxBorder,
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 10,
    margin: 7,
    gap: 10,
    justifyContent: 'space-around',
  },
  blueBoxTasks: {
    width: 355,
    height: 'auto',
    backgroundColor: theme.colors.blueBoxBackground,
    borderColor: theme.colors.blueBoxBorder,
    borderWidth: 1.5,
    alignSelf: 'center',
    borderRadius: 20,
    justifyContent: 'space-around',
    padding: 25,
    margin: 7,
  },
  blueBoxChat: {
    width: 'auto',
    height: 'auto',
    backgroundColor: theme.colors.blueBoxBackground,
    borderColor: theme.colors.blueBoxBorder,
    borderWidth: 1.5,
    alignSelf: 'flex-start',

    borderTopLeftRadius: 0,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    justifyContent: 'space-around',
    padding: 10,
    margin: 7,
    maxWidth: Dimensions.get('screen').width - 150,
  },
  greyBoxChat: {
    width: 'auto',
    height: 'auto',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: theme.colors.grey,
    borderColor: theme.colors.greyBorderColor,
    borderWidth: 1.5,
    alignSelf: 'flex-end',
    padding: 10,
    margin: 4,
    maxWidth: Dimensions.get('screen').width - 150,
  },
});
